StringBuilder gcode = new StringBuilder();

// CURVE_SPEED will be calculated as 80% of TOOL_SPEED_MM_PER_MIN
int CURVE_TENSION = 0;

void resetGcode() {
  gcode = new StringBuilder();
}

void headGcode() {
  int curveSpeed = int(TOOL_SPEED_MM_PER_MIN * 0.8);
  gcode.append("; G-code generated by GTracker - Samuele Coppede - gcode.pro\n");
  gcode.append("; Work Area: " + int(PRINT_W_MM) + "x" + int(PRINT_H_MM) + " mm\n");
  gcode.append("; Base Speed: " + TOOL_SPEED_MM_PER_MIN + " mm/min\n");
  gcode.append("; Curve Speed: " + curveSpeed + " mm/min (-20%)\n");
  gcode.append("; Curve Tension: " + CURVE_TENSION + "\n");
  gcode.append("; Estimated Time: 0m 26s\n"); // Placeholder
  gcode.append("G21 ; Set Units to Millimeters\n");
  gcode.append("G17 ; Set Plane Selection to XY\n");
  gcode.append("G90 ; Set Absolute Positioning\n");
  gcode.append("F" + TOOL_SPEED_MM_PER_MIN + "  ; Set Speed  mm/min \n");
  gcode.append("G00 Z" + TOOL_UP_MM + " ; pen up\n");
  gcode.append("G92 X0 Y0 ; consider current position as 0,0\n");
  gcode.append("\n");
}

void startPathGcode(int pathIndex, color c) {
  String hexColor = hex(c, 6);
  gcode.append("; --- Path " + (pathIndex + 1) + " (Color: #" + hexColor + ") ---\n");
}

void initialMoveGcode(float x, float y) {
  gcode.append("G0 Z" + TOOL_UP_MM + " ;\n");
  gcode.append("G0 X" + nf(x, 0, 3) + " Y" + nf(y, 0, 3) + " ; Initial position path\n");
  gcode.append("G0 Z" + TOOL_DOWN_MM + " ;\n");
}

void linearMoveGcode(float x, float y) {
  gcode.append("F" + TOOL_SPEED_MM_PER_MIN + " ; Linear speed\n");
  gcode.append("G1 X" + nf(x, 0, 3) + " Y" + nf(y, 0, 3) + "\n");
}

void curveMoveGcode(float x, float y) {
  int curveSpeed = int(TOOL_SPEED_MM_PER_MIN * 0.8);
  gcode.append("F" + curveSpeed + " ; Curve speed\n");
  gcode.append("G1 X" + nf(x, 0, 3) + " Y" + nf(y, 0, 3) + "\n");
}

// Generic move that doesn't force speed (assumes current speed is fine)
void moveGcode(float x, float y) {
   gcode.append("G1 X" + nf(x, 0, 3) + " Y" + nf(y, 0, 3) + "\n");
}


void footGcode() {
  gcode.append("\n");
  gcode.append("; End of program\n");
  gcode.append("G0 Z" + TOOL_UP_MM + " ;\n");
  gcode.append("G00 X0 Y0\n");
}

void saveGcode(String filename) {
  String[] lines = gcode.toString().split("\n");
  saveStrings("output/" + filename + ".gcode", lines);
}
