StringBuilder gcode = new StringBuilder();

// CURVE_SPEED will be calculated as 80% of TOOL_SPEED_MM_PER_MIN
float CURVE_TENSION = 0.39;

float lastGcodeX = -9999;
float lastGcodeY = -9999;
int currentGcodeSpeed = -1;

String fmt(float val) {
  return nf(val, 0, 3).replace(',', '.');
}

void resetGcode() {
  gcode = new StringBuilder();
  lastGcodeX = -9999;
  lastGcodeY = -9999;
  currentGcodeSpeed = -1;
}

// Draw a continuous line segment. Handles jumps if necessary.
void gcodeLine(float x1, float y1, float x2, float y2) {
  float dist = dist(lastGcodeX, lastGcodeY, x1, y1);
  if (dist > 0.1) {
    // Jump
    gcode.append("G0 Z" + TOOL_UP_MM + "\n");
    gcode.append("G0 X" + fmt(x1) + " Y" + fmt(y1) + "\n");
    gcode.append("G0 Z" + TOOL_DOWN_MM + "\n");
    // Force speed reset after jump just in case, or let the logic below handle it?
    // Usually G0 doesn't change F, but let's be safe relative to tracking.
    // Logic below handles it if currentGcodeSpeed differs.
  }
  
  int targetSpeed = TOOL_SPEED_MM_PER_MIN;
  if(currentGcodeSpeed != targetSpeed){
    gcode.append("F" + targetSpeed + "\n");
    currentGcodeSpeed = targetSpeed;
  }
  
  gcode.append("G1 X" + fmt(x2) + " Y" + fmt(y2) + "\n");
  lastGcodeX = x2;
  lastGcodeY = y2;
}

// Draw a continuous curve segment (using G1 approximations). Handles jumps.
void gcodeCurveLine(float x1, float y1, float x2, float y2) {
   float dist = dist(lastGcodeX, lastGcodeY, x1, y1);
   
   int curveSpeed = TOOL_SPEED_MM_PER_MIN;
   if(reduceCurveSpeed){
     curveSpeed = int(TOOL_SPEED_MM_PER_MIN * 0.8);
   }

   if (dist > 0.1) {
    gcode.append("G0 Z" + TOOL_UP_MM + "\n");
    gcode.append("G0 X" + fmt(x1) + " Y" + fmt(y1) + "\n");
    gcode.append("G0 Z" + TOOL_DOWN_MM + "\n");
  } 
  
  if(currentGcodeSpeed != curveSpeed){
    gcode.append("F" + curveSpeed + "\n");
    currentGcodeSpeed = curveSpeed;
  }
  
  gcode.append("G1 X" + fmt(x2) + " Y" + fmt(y2) + "\n");
  
  lastGcodeX = x2;
  lastGcodeY = y2;
}

void headGcode() {
  int curveSpeed = TOOL_SPEED_MM_PER_MIN;
  if(reduceCurveSpeed){
     curveSpeed = int(TOOL_SPEED_MM_PER_MIN * 0.8);
  }
  
  gcode.append("; G-code generated by GTracker - Samuele Coppede - gcode.pro\n");
  gcode.append("; Work Area: " + int(PRINT_W_MM) + "x" + int(PRINT_H_MM) + " mm\n");
  gcode.append("; Base Speed: " + TOOL_SPEED_MM_PER_MIN + " mm/min\n");
  if(reduceCurveSpeed){
    gcode.append("; Curve Speed: " + curveSpeed + " mm/min (-20%)\n");
  } else {
    gcode.append("; Curve Speed: " + curveSpeed + " mm/min (100%)\n");
  }
  gcode.append("; Curve Tension: " + CURVE_TENSION + "\n");
  gcode.append("; Estimated Time: 0m 26s\n"); // Placeholder
  gcode.append("G21 ; Set Units to Millimeters\n");
  gcode.append("G17 ; Set Plane Selection to XY\n");
  gcode.append("G90 ; Set Absolute Positioning\n");
  gcode.append("F" + TOOL_SPEED_MM_PER_MIN + "  ; Set Speed  mm/min \n");
  currentGcodeSpeed = TOOL_SPEED_MM_PER_MIN;
  
  gcode.append("G00 Z" + TOOL_UP_MM + " ; pen up\n");
  gcode.append("G92 X0 Y0 ; consider current position as 0,0\n");
  gcode.append("\n");
}

void startPathGcode(int pathIndex, color c) {
  String hexColor = hex(c, 6);
  gcode.append("; --- Path " + (pathIndex + 1) + " (Color: #" + hexColor + ") ---\n");
}

void initialMoveGcode(float x, float y) {
  gcode.append("G0 Z" + TOOL_UP_MM + " ;\n");
  gcode.append("G0 X" + fmt(x) + " Y" + fmt(y) + " ; Initial position path\n");
  gcode.append("G0 Z" + TOOL_DOWN_MM + " ;\n");
}

void linearMoveGcode(float x, float y) {
  gcode.append("F" + TOOL_SPEED_MM_PER_MIN + " ; Linear speed\n");
  gcode.append("G1 X" + fmt(x) + " Y" + fmt(y) + "\n");
}

void curveMoveGcode(float x, float y) {
  int curveSpeed = int(TOOL_SPEED_MM_PER_MIN * 0.8);
  gcode.append("F" + curveSpeed + " ; Curve speed\n");
  gcode.append("G1 X" + fmt(x) + " Y" + fmt(y) + "\n");
}

// Generic move that doesn't force speed (assumes current speed is fine)
void moveGcode(float x, float y) {
   gcode.append("G1 X" + fmt(x) + " Y" + fmt(y) + "\n");
}


void footGcode() {
  gcode.append("\n");
  gcode.append("; End of program\n");
  gcode.append("G0 Z" + TOOL_UP_MM + " ;\n");
  gcode.append("G00 X0 Y0\n");
}

void saveGcode(String filename) {
  String[] lines = gcode.toString().split("\n");
  saveStrings("output/" + filename + ".gcode", lines);
}
