#!/usr/bin/env bash
set -euo pipefail

# Uso:
#   ./svg2gcode.sh "file.svg" [penup] [pendown] [speed] [width] [height] [margin] [connect]
#
# Esempio:
#   ./svg2gcode.sh "2026-1-10 16-9-6.svg" 0 7 2000 297 420 10 true
#
# Default se omessi:
#   penup=0 pendown=7 speed=2000 width=297 height=420 margin=10 connect=false

if [[ $# -lt 1 ]]; then
  echo "Uso: $0 \"input.svg\" [penup] [pendown] [speed] [width] [height] [margin] [connect]"
  exit 1
fi

INPUT="$1"
PENUP="${2:-0}"
PENDOWN="${3:-7}"
SPEED="${4:-2000}"
WIDTH="${5:-297}"
HEIGHT="${6:-420}"
MARGIN="${7:-10}"
CONNECT="${8:-false}"

if [[ ! -f "$INPUT" ]]; then
  echo "Errore: file non trovato: $INPUT"
  exit 1
fi

# output: stesso nome, estensione .gcode
BASENAME="${INPUT%.*}"
OUTPUT="${BASENAME}.gcode"

TMP_CFG="$(mktemp /tmp/vpype-gcode-XXXXXX.toml)"
cleanup() { rm -f "$TMP_CFG"; }
trap cleanup EXIT

cat > "$TMP_CFG" <<EOF
[gwrite.default]
unit = "mm"
invert_y = false
default_values = { vp_penup = "${PENUP}", vp_pendown = "${PENDOWN}", vp_speed = ${SPEED} }

document_start = """; G-code generated by vpype-gcode
G21 ; Set Units to Millimeters
G17 ; Set Plane Selection to XY
G90 ; Set Absolute Positioning
F{vp_speed:d}  ; Set Speed  mm/min
G00 Z{vp_penup} ; pen up
G92 X0 Y0 ; consider current position as 0,0
"""

layer_start = "; --- Layer {layer_index1:d} ---\\n"

segment_first = """G0 Z{vp_penup} ;
G0 X{x:.3f} Y{y:.3f} ; Initial position
G0 Z{vp_pendown} ;
G4 S10 ; PAUSA 10 Secondi
F{vp_speed:d} ; Linear speed
"""
  
segment = """G1 X{x:.3f} Y{y:.3f}\\n"""

line_end = """G0 Z{vp_penup} ; pen up\\n\\n"""

document_end = """G0 Z{vp_penup} ;
"""
EOF
# G00 X0 Y0; questo era dopo il document_end, 
vpype -c "$TMP_CFG" \
  read "$INPUT" \
  linemerge --tolerance 0.1mm \
  linesimplify --tolerance 0.05mm \
  linesort \
  rotate 90 \
  layout --fit-to-margins ${MARGIN}mm --align center --valign center ${WIDTH}mmx${HEIGHT}mm \
  gwrite -p default \
  "$OUTPUT"

# Clean registration marks
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
"$DIR/remove_marks.sh" "$OUTPUT"

# Se richiesto, esegui connect_paths.py per unire i tracciati
if [[ "$CONNECT" == "true" ]]; then
  TMP_OUTPUT="${OUTPUT%.gcode}_tmp.gcode"
  mv "$OUTPUT" "$TMP_OUTPUT"
  
  echo "Collegamento tracciati con connect_paths.py..."
  python3 "$DIR/connect_paths.py" "$TMP_OUTPUT" "$OUTPUT"
  
  # Rimuovi il file temporaneo
  rm "$TMP_OUTPUT"
  
  echo "OK: creato \"$OUTPUT\" con tracciati collegati (penup=$PENUP pendown=$PENDOWN speed=$SPEED size=${WIDTH}x${HEIGHT}mm)"
else
  echo "OK: creato \"$OUTPUT\" (penup=$PENUP pendown=$PENDOWN speed=$SPEED size=${WIDTH}x${HEIGHT}mm)"
fi